baseURL = 'https://sun-kid.com/'
languageCode = 'en-us'
title = 'Sun Kid'
theme = 'smol'

# Parameters
[params]
    subtitle = ""
    dateFmt = "02.01.2006 15:04"
    mainSections = ["posts"]
    customCSS = ["css/custom.css"]  # Add this line to include your custom CSS

# Header
[menu]
  [[menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts/"
        weight = 1 


  [[menu.main]]
        identifier = "categories"
        name = "Categories"
        url = "/categories/"
        weight = 3
